const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const productSchema = Schema(
  {
    sku: { type: String, required: true, unique: true },
    name: { type: String, required: true },
    image: { type: Array, required: true },
    category: { type: Array, required: true },
    description: { type: String, required: true },
    price: { type: Number, required: true },
    stock: { type: Object, required: true },
    height: { type: Number, required: true },
    weight: { type: Number, required: true }, 
    status: { type: String, default: "active" },
    isDeleted: { type: Boolean, default: false },
    washMethods: [
      {
        label: { type: String, required: true },
        value: { type: String, required: true },
      },
    ],
    
    // AI 추출 정보 추가
    aiExtractedInfo: {
      // 카테고리 정보
      category: {
        primaryCategory: { type: String }, // "Outer", "Top", "Pants", "Shoes", "Acc"
        subCategory: { type: String },     // "jacket", "coat", "t-shirt" 등
        confidence: { type: Number }       // 0.0 ~ 1.0
      },
      
      // 색상 정보
      colors: {
        primaryColor: { type: String },    // "navy blue", "black" 등
        colorPalette: [{ type: String }],  // ["navy blue", "white", "light gray"]
        colorConfidences: [{ type: Number }] // [0.85, 0.12, 0.03]
      },
      
      // 패턴 정보
      pattern: {
        type: { type: String },           // "plain", "striped", "checkered" 등
        confidence: { type: Number }
      },
      
      // 스타일 정보
      style: {
        type: { type: String },           // "casual", "formal", "sporty" 등
        confidence: { type: Number }
      },
      
      // 소재 정보
      material: {
        type: { type: String },           // "cotton", "polyester", "wool" 등
        confidence: { type: Number }
      },
      
      // 자동 생성 텍스트
      autoGeneratedText: {
        name: { type: String },           // AI 생성 상품명
        description: { type: String },    // AI 생성 상품 설명
        tags: [{ type: String }]         // AI 생성 태그
      },
      
      // 세탁 방법 추정
      washMethodEstimation: {
        estimatedMaterial: { type: String },
        estimatedMethods: [{ type: String }],
        confidence: { type: Number },
        reason: { type: String }
      },
      
      // AI 분석 결과 요약
      summary: { type: String }
    },
    
    // AI 분석 메타데이터
    aiAnalysis: {
      confidence: { type: Number },       // 전체 분석 신뢰도
      analyzedAt: { type: Date, default: Date.now },
      modelVersion: { type: String, default: "CLIP-ViT-B/32" }
    },
    
    // CLIP 특징벡터 저장 (선택사항)
    clipFeatures: {
      imageVector: { type: [Number] },    // 단일 이미지의 512차원 벡터
      vectorDimension: { type: Number, default: 512 }
    }
  },
  { timestamps: true }
);

productSchema.methods.toJSON = function () {
  const obj = this._doc;
  delete obj._v;
  delete obj.updateAt;
  delete obj.createAt;
  return obj;
};

const Product = mongoose.model("Product", productSchema);
module.exports = Product;
